### ISSUE TITLE
CSS example with tags and nonumber

### ISSUE THREAD

**Issue by tlienart** [tlienart/FranklinTemplates.jl#73]
```css
body { counter-reset: eqnum; }
.katex { font-size: 1em !important; }
/* overwrite katex settings */
.katex-display .katex {
    display: inline-block; } 
.katex-display::after {
    counter-increment: eqnum;
    content: "(" counter(eqnum) ")";
    position: relative;
    float: right;
    padding-right: 5px; }
.no-number .katex-display::after {
  counter-increment: nothing;
  content: "";
}
.no-number .katex-display .katex {
  display: block;
  margin: 1em 0;
  text-align: center;
}
```

<img width="765" alt="Screen Shot 2020-05-27 at 10 14 39" src="https://user-images.githubusercontent.com/10897531/82995009-4fa85780-a003-11ea-8428-0261949c165e.png">
