### ISSUE TITLE
KaTeX numbering CSS improvement

### ISSUE THREAD

**Issue by tlienart** [tlienart/FranklinTemplates.jl#85]
https://github.com/KaTeX/KaTeX/issues/1785#issuecomment-673651262

```css
.katex-display {
  position: relative;
  counter-increment: eqn;
}

.katex-display::after {
  content: "(" counter(eqn) ")";
  position: absolute;
  display: block;
  top: 50%;
  transform: translateY(-50%);
  right: 0;
}
```

should check whether the `translateY` is well supported but it looks like it is

**looks like it** https://caniuse.com/#search=translateY
